name: Secure Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NON_SENSITIVE_VAR: "App_v1" # Variable no sensible accesible en todo el workflow

permissions:
  contents: read # Permiso mínimo a nivel workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permiso mínimo a nivel job
 steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Demostrar diferencia entre vars y secrets
        env:
          MI_SECRETO: ${{ secrets.API_SECRET }}
        run: |
          echo "La variable no sensible muestra su valor: $NON_SENSITIVE_VAR"
          echo "El secreto por seguridad se oculta: $MI_SECRETO"
          
      - name: Construir aplicación y validar
        run: echo "Tests validados correctamente."
